# Generated by Django 5.0 on 2023-12-08 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='carrera')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 12, 8, 11, 15, 2, 631900))),
                ('comision', models.IntegerField(unique=True)),
            ],
        ),
    ]
