# Generated by Django 5.0 on 2023-12-11 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_carrera_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 11, 39, 53, 140121)),
        ),
    ]
