# Generated by Django 5.0 on 2023-12-12 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_carrera_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 20, 36, 21, 596140)),
        ),
    ]
